site_name: Ricardo - Strive

theme:
   name: material
   language: en
plugins:
  - search
nav:
  - Introduction: 'index.md'
  - Examples: 'examples.md'
  - Contributing: 'contributing.md'
  - Models: 'models.md'
